services:
  - docker

before_install:
- docker pull postgres:9.6

language: scala

scala:
   - 2.12.2

before_script: cd alerts-server

script:
- sbt clean coverage test coverageReport

after_success:
- bash < (curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
- sbt coverageAggregate codacyCoverage

