package com.alexitc.coinalerts.errors

import com.alexitc.playsonify.models.{ConflictError, NotFoundError}

sealed trait UserVerificationTokenError
case object UserVerificationTokenNotFoundError extends UserVerificationTokenError with NotFoundError
case object UserVerificationTokenAlreadyExistsError extends UserVerificationTokenError with ConflictError
